services:
    laravel-docker:
        container_name: adams-store
        build: .
        volumes:
            - .:/var/www/html
        ports:
            - 9000:80
        depends_on:
            - mysql_db
        networks:
            - app-network

    mysql_db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 9001:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql_db
        depends_on:
            - mysql_db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
